jobs:
  pr_review_submitted:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/pr-review-labels-action@4ef8743729b77c6eff5dc920857fc102e4036aa3

name: PR Review Submitted

on:
  pull_request_review:
    types:
      - submitted
