jobs:
  pr_review_submitted:
    permissions: {}
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/pr-review-labels-action@fc1cc3089bf2c523bd2b04f0955016c9e5c5e3b7

name: PR Review Submitted

on:
  pull_request_review:
    types:
      - submitted
