jobs:
  pr_review_labels:
    permissions:
      actions: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: JoshuaKGoldberg/pr-review-labels-action@5b3bfb1bfba9a47964590b54023f0e2e2ba13d9b

name: PR Review Labels

on:
  pull_request_target:
    types:
      - review_requested
  workflow_run:
    types:
      - completed
    workflows:
      - PR Review Submitted
